### ISSUE TITLE
メンテナンスされていない状態を明示して下さい

### ISSUE THREAD

**Issue by CRC32EX** [yuuki0xff/conoha-cli#12]
> 私は現在はConoHaを利用しておらず、conoha-cliはメンテナンスされていない状態です。

リポジトリの設定から`Archive this repository`を有効にする事を検討してください。
こちらのコメント https://github.com/yuuki0xff/conoha-cli/pull/11#issuecomment-1344242689 を確認しなければメンテナンス状況が分からない状態です。

**Comment by yuuki0xff** [comment]
先程、READMEにも記載しました。

[pypiパッケージ](https://pypi.org/project/conoha-cli/) の説明文は更新できないようです。
最後のリリースを実施した後に、リポジトリをアーカイブしようかなと考えています。

**Comment by yuuki0xff** [comment]
[conoha-cli 0.3.0](https://pypi.org/project/conoha-cli/0.3.0/) の公開完了。

特に指摘事項がなければ、明日このリポジトリをアーカイブします。

**Comment by CRC32EX** [comment]
ご対応ありがとうございます。
よろしくお願いします。
